name: Coq Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y opam git autoconf g++ m4

      - name: Initialize OPAM and set up Coq environment
        run: |
          # Initialize opam non-interactively
          opam init -y --disable-sandboxing
          # Create a new switch with Coq 8.14.1
          opam switch create coq-8.14.1 --packages=coq.8.14.1
          eval $(opam env --switch=coq-8.14.1)
          opam update
          # Install Coquelicot (version 3.2.0 is compatible with Coq 8.14.1)
          opam install -y coq-coquelicot.3.2.0
          # Refresh environment variables
          eval $(opam env --switch=coq-8.14.1)

      - name: Run Coq Verification
        run: |
          eval $(opam env --switch=coq-8.14.1)
          # Compile all Coq source files in the 'coq' directory
          find coq -name '*.v' -print0 | xargs -0 -n1 coqc
