name: Coq Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install opam and Coq
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          # Initialize opam (disable sandboxing for compatibility with GitHub runners)
          opam init -y --disable-sandboxing
          # Create a switch with Coq 8.17.1 using the explicit package version
          opam switch create coq-8.17.1 --packages=coq.8.17.1
          eval $(opam env)
          # Install Coquelicot, which is needed by your proofs
          opam install -y coquelicot

      - name: Run Coq Verification
        run: |
          eval $(opam env)
          # Optionally, if you have a Makefile, use: make -C coq
          find coq -name '*.v' -print0 | xargs -0 -n1 coqc
