name: Coq Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Coq and opam
        uses: coq-community/setup-coq@v2
        with:
          coq-version: '8.17'   # Adjust this version to match your project’s Coq version

      - name: Install Coquelicot dependency
        run: |
          opam update
          opam install coquelicot

      - name: Run Coq Verification
        run: |
          find coq -name '*.v' -print0 | xargs -0 -n1 coqc
