name: Coq Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install opam and Coq
        run: |
          sudo apt-get update
          sudo apt-get install -y opam
          opam init -y --disable-sandboxing
          # Create a switch using Coq 8.14.1 (adjust if needed)
          opam switch create coq-8.14.1 --packages=coq.8.14.1
          eval $(opam env)
          # Install Coquelicot which is available for Coq 8.14.1
          opam install -y coquelicot

      - name: Run Coq Verification
        run: |
          eval $(opam env)
          # If you have a Makefile in your 'coq' directory, you can use: make -C coq
          find coq -name '*.v' -print0 | xargs -0 -n1 coqc
